- name: Clone a private repository into /opt.
  command: sudo git clone https://github.com/IlyaRogachov/pythonwebdone.git  /tmp/repo

- name: return motd to registered var
  command: helm install --name mysql /tmp/repo/chart_mysql/mysql
